version: '3.8'

services:
  # Postgres database
  postgres:
    image: postgres:16-alpine
    container_name: perfolio-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: perfolio
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5
    command: ['postgres', '-c', 'log_statement=all']

  # Redis for caching (optional - disabled by default, enable when needed)
  # redis:
  #   image: redis:7-alpine
  #   container_name: perfolio-redis
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis_data:/data
  #   healthcheck:
  #     test: ["CMD", "redis-cli", "ping"]
  #     interval: 5s
  #     timeout: 5s
  #     retries: 5

volumes:
  postgres_data:
  redis_data:
